# Generated by Django 6.0.2 on 2026-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Sci-Fi', 'Sci-Fi'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Others', 'Others')], default='Fiction', max_length=50)),
                ('published_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed')], default='available', max_length=20)),
            ],
        ),
    ]
